"""init

Revision ID: 96751a710f36
Revises: 
Create Date: 2026-02-16 10:00:49.780921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96751a710f36'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('datasets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False, comment='Auto-incrementing version number'),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Only one dataset should be active'),
    sa.Column('uploaded_by', sa.Integer(), nullable=True, comment='User who uploaded this version'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True, comment='SHA-256 of the uploaded CSV content'),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_datasets_is_active'), ['is_active'], unique=False)

    op.create_table('analysis_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False, comment='FK to datasets – links result to the exact dataset version'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('k', sa.Integer(), nullable=False, comment='Number of clusters used'),
    sa.Column('pca_components', sa.JSON(), nullable=False),
    sa.Column('pca_loadings', sa.JSON(), nullable=False),
    sa.Column('pca_explained_variance', sa.JSON(), nullable=False),
    sa.Column('cluster_assignments', sa.JSON(), nullable=False, comment='{ province_name: cluster_id }'),
    sa.Column('cluster_centers', sa.JSON(), nullable=False),
    sa.Column('silhouette_score', sa.Float(), nullable=False),
    sa.Column('inertia', sa.Float(), nullable=False),
    sa.Column('davies_bouldin', sa.Float(), nullable=False),
    sa.Column('calinski_harabasz', sa.Float(), nullable=False),
    sa.Column('cluster_summary', sa.JSON(), nullable=True),
    sa.Column('k_evaluation', sa.JSON(), nullable=True),
    sa.Column('log_transformed', sa.Boolean(), nullable=True),
    sa.Column('transform_info', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_results_dataset_id'), ['dataset_id'], unique=False)

    op.create_table('provinces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False, comment='FK to datasets – scopes rows to a specific dataset version'),
    sa.Column('provinsi', sa.String(length=100), nullable=False),
    sa.Column('pmdn_rp', sa.Float(), nullable=False, comment='PMDN / Investasi Dalam Negeri (Rp)'),
    sa.Column('fdi_rp', sa.Float(), nullable=False, comment='PMA / Foreign Direct Investment (Rp)'),
    sa.Column('pdrb_per_kapita', sa.Float(), nullable=False),
    sa.Column('ipm', sa.Float(), nullable=False),
    sa.Column('kemiskinan', sa.Float(), nullable=False),
    sa.Column('akses_listrik', sa.Float(), nullable=False),
    sa.Column('tpt', sa.Float(), nullable=False, comment='Tingkat Pengangguran Terbuka (%)'),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_id', 'provinsi', name='uq_province_per_dataset')
    )
    with op.batch_alter_table('provinces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provinces_dataset_id'), ['dataset_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('provinces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provinces_dataset_id'))

    op.drop_table('provinces')
    with op.batch_alter_table('analysis_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_results_dataset_id'))

    op.drop_table('analysis_results')
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_datasets_is_active'))

    op.drop_table('datasets')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
